
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estoque
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    descricao text,
    quantidade integer NOT NULL,
    valor real NOT NULL,
    dt_criacao date NOT NULL DEFAULT now(),
    dt_att date,
    dt_validade date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.frotas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    marca text NOT NULL,
    modelo text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.parceiros
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.aumigo
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    dt_inicio date NOT NULL DEFAULT now(),
    dt_fim date,
    status boolean NOT NULL,
    id_parceiro uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    telefone character varying(11) NOT NULL,
    idade integer NOT NULL,
    email text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.animais
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pet_dono
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    id_animal uuid NOT NULL,
    id_cliente uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.funcionarios
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    email text NOT NULL,
    senha text NOT NULL,
    id_cargo uuid,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cargo_func
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coletas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    dt_coleta date NOT NULL,
    endereco text NOT NULL,
    id_cliente uuid NOT NULL,
    id_animal uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.consultas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    data date NOT NULL,
    id_animal uuid NOT NULL,
    id_medico uuid NOT NULL,
    id_servico uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logs_sistema
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    op_realizada text NOT NULL,
    descricao text NOT NULL,
    data date NOT NULL DEFAULT now(),
    id_funcionario uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.registro_ponto
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    data date NOT NULL,
    id_funcionario uuid NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vendas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    id_item uuid NOT NULL,
    id_funcionario uuid NOT NULL,
    id_cliente uuid NOT NULL,
    data date NOT NULL DEFAULT now(),
    PRIMARY KEY (id, id_item, id_funci)
);

CREATE TABLE IF NOT EXISTS public.servicos
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.aumigo
    ADD CONSTRAINT id_parceiro FOREIGN KEY (id_parceiro)
    REFERENCES public.parceiros (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pet_dono
    ADD CONSTRAINT id_animal FOREIGN KEY (id_animal)
    REFERENCES public.animais (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pet_dono
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.funcionarios
    ADD CONSTRAINT id_cargo_func FOREIGN KEY (id_cargo)
    REFERENCES public.cargo_func (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.coletas
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.coletas
    ADD CONSTRAINT id_animal FOREIGN KEY (id_animal)
    REFERENCES public.animais (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.consultas
    ADD CONSTRAINT id_animal FOREIGN KEY (id_animal)
    REFERENCES public.animais (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.consultas
    ADD CONSTRAINT id_medico FOREIGN KEY (id_medico)
    REFERENCES public.funcionarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.consultas
    ADD CONSTRAINT id_servico FOREIGN KEY (id_servico)
    REFERENCES public.servicos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.logs_sistema
    ADD CONSTRAINT id_funcionario FOREIGN KEY (id_funcionario)
    REFERENCES public.funcionarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.registro_ponto
    ADD CONSTRAINT id_funcionario FOREIGN KEY (id_funcionario)
    REFERENCES public.funcionarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT id_item FOREIGN KEY (id_item)
    REFERENCES public.estoque (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT id_func FOREIGN KEY (id_funcionario)
    REFERENCES public.funcionarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vendas
    ADD CONSTRAINT id_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;